version: '3.7'
services:
    app01:
        shm_size: '1000000000'
        build:
            context: ./app
            args:
                - "FLASK_ENV=${FLASK_ENV:-production}"
                - "NODE_ENV=${NODE_ENV:-production}"
        tty: true
        volumes:
            - './app/src:/home/lagoa'
    nginx:
        build: ./nginx
        tty: true
        links:
            - app01
        ports:
            - '80:80'
